@startuml

skinparam classAttributeFontName Monospaced
skinparam classBackgroundColor #EFF2FB
skinparam classBorderColor #D8D8D8
skinparam packageBorderColor #BDBDBD
skinparam classArrowColor #0B615E
skinparam shadowing false

'skinparam monochrome true
'skinparam nodesep 100
'skinparam ranksep 100



package pyoko{


'note  "All <color:black><b> (M)odels</b></color> extends <b>Base</b> and <b>Model</b>" as n1 #orchid
'n1 .. Base
'n1 .. Model

class DBObjects{

- __client
- _cfg
- _data_type
- _new_record_value
- _riak_cache
- _solr_cache
- _solr_locked
- _solr_params
- _solr_query
--
+ set_bucket()
+ count_bucket()
+ new()
+ save()
+ filter()
+ get()
+ count()
+ fields()
+ solr()
+ data()
- __iter__()
- __len__()
- __getitem__()
- __deepcopy__()
- _save_model()
- _get_from_db()
- _get_data_from_db()
- _get()
- _params()
- _compile_query()
- _process_params()
- _exec_query()
}
    class Base{
    - _DEFAULT_BASE_FIELDS
  |_ archived Boolean
  |_ timestamp DateTime
  |_ deleted Boolean
    + save()
    + delete()
    + objects = DBObjects()
    }
    class Model{
    + clean_data()
    - _load_data()

    }
    class AbstractBase{
    }
    class ListModel extends Model{
    }
Base --o DBObjects
}


@enduml
