@startuml

skinparam classAttributeFontName Monospaced
skinparam classBackgroundColor #EFF2FB
skinparam classBorderColor #D8D8D8
skinparam packageBorderColor #BDBDBD
skinparam classArrowColor #0B615E
skinparam shadowing false

package SpiffWorkflow{
class Workflow{
+ completed_event
+ data
+ debug
+ last_task
+ locks
+ outer_workflow
+ spec
+ success
+ task_tree
--
- _get_waiting_tasks()
- _task_completed_notify()
- _get_mutex()
+ is_completed()
+ get_data()
+ cancel()
+ get_task_spec_from_name()
+ get_task()
+ get_tasks_from_spec_name()
+ get_tasks()
+ complete_task_from_id()
+ complete_next()
+ complete_all()
+ get_dump()
+ dump()
+ serialize()
+ deserialize()
}
class BPMNWorkflow extends Workflow{
- _is_busy_with_restore
- _is_engine_task
- _task_completed_notify
- _task_cancelled_notify
- _busy_with_restore
- name
- read_only
- script_engine
--
+ accept_message()
+ do_engine_steps()
+ refresh_waiting_tasks()
+ get_ready_user_tasks()
+ get_waiting_tasks()
}
class BPMNParser{
+ OVERRIDE_PARSER_CLASSES
+ PARSER_CLASSES
+ PROCESS_PARSER_CLASS
+ WORKFLOW_CLASS
+ process_parsers
+ process_parsers_by_name
--
+ get_process_parser()
+ add_bpmn_file()
+ add_bpmn_files_by_glob()
+ add_bpmn_files()
+ add_bpmn_xml()
+ parse_condition()
+ parse_documentation()
+ get_spec()
- _get_parser_class()
- _parse_condition()
- _parse_documentation()
}
BPMNParser --o BPMNWorkflow
}

BPMNWorkflow --o zengine.ZEngine

package zengine{
    class ZEngine{
        + **workflow(BPMNWorkflow)**
        + ACTIVITY_MODULES_PATH
        + WORKFLOW_DIRECTORY
        + activities
        + current
        + workflow_spec
        --
        - _load_workflow()
        - _save_workflow()
        + create_workflow()
        + load_or_create_workflow()
        + get_worfklow_spec()
        + serialize_workflow()
        + save_workflow()
        + load_workflow()
        + set_current()
        + complete_current_task()
        + run()
        + run_activity()
        + process_activities()
        + cleanup()
    }
}


@enduml
